kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drivetester-db
  namespace: drivetester
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: odf-lvm-vg1
  volumeMode: Filesystem
